---

image: debian:bookworm-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Pin hugo version from buster for guardianproject.info
.hugo-template: &hugo-template |
  printf 'Package: hugo\nPin: version 0.5*\nPin-Priority: 1000\n' > /etc/apt/preferences.d/hugo
  echo 'deb https://snapshot.debian.org/archive/debian/20240630T000000Z/ buster main' > /etc/apt/sources.list.d/buster.list
  apt-get update
  apt-get -qy install --no-install-recommends hugo
  sed -i "s,^baseURL\x3a.*,baseURL\x3a https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/," config.yaml

release:
  image: registry.gitlab.com/fdroid/fdroidserver:buildserver-trixie
  script:
    - apt-get update
    - apt-get dist-upgrade

    - test -n "$fdroidserver" || source /etc/profile.d/bsenv.sh

    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/*.apk

test:
  script:
    - *hugo-template
    - hugo
  except:
    - master

pages:
  script:
    - *hugo-template
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master
